apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-config
  namespace: argocd
  labels:
    environment: core
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/fcsf/DevOps.git
    targetRevision: HEAD
    path: environments/prod/core


  destination:
    name: in-cluster
    namespace: argocd

  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  #     allowEmpty: true