---
apiVersion: v1
kind: Secret
metadata:
  name: tharpool-test-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: tharpool-test-repo
  type: git
  url: https://github.com/tharpooljha/test
  password: fcsf
