apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.5.4/manifests/ha/install.yaml
- vault-configuration.yaml
- repository.yaml
- argo-role.yaml
#- cmp-plugin.yaml

patchesStrategicMerge:
- argocd-secret.yaml
#- argocd-repo-server.yaml






