apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: argocd-appset
spec:
  generators:
  - list:
      elements:
      - cluster: core
        cluster-name: in-cluster
        overlay: overlays/core
        targetRevision: HEAD



  template:
    metadata:
      name: '{{cluster}}-argo'
      labels:
        app: '{{cluster}}-argo'
    spec:
      project: prod
      source:
        repoURL: https://github.com/fcsf/DevOps.git
        targetRevision: '{{ targetRevision }}'
        path: apps/argocd/prod/{{overlay}}
      destination:
        name: '{{ cluster-name }}'
        namespace: argocd