apiVersion: v1
kind: Secret
metadata:
  name: gitops-repo
  namespace: argocd  
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: devops-repo
  url: https://github.com/tharpooljha/gitops.git
#  password: <path:kv-v2/data/argocd#github_token>  
  password: fcsf
---
apiVersion: v1
kind: Secret
metadata:
  name: artifactory-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: artifactory-helm-repo
  type: helm
  url: https://artifactory
#  password: <path:kv-v2/data/argocd#artifactory_apikey>
  username: fcsf
  password: fcsf
