kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  annotations:
    avp.kubernetes.io/path: "kv-v2/data/argocd"
type: Opaque
stringData:
  sample-secret: <password>
  password: <path:kv-v2/data/argocd#password>
---
kind: Secret
apiVersion: v1
metadata:
  name: example-secret-dev
  namespace: dev
  annotations:
    avp.kubernetes.io/path: "kv-v2/data/argocd"
type: Opaque
stringData:
  sample-secret: <password>
  password: <path:kv-v2/data/argocd#password>
